### ISSUE TITLE
Wrong keywords in forwardingList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationLayerTopology#308]
I noticed that in the forwarding list there are keywords "server-name" and "service-name".
In the template from the ApplicationPattern I only see "server-name", so I guess this might be wrong as I would expect this should be "server-name" everywhere...

Example:
```
  - forwarding-name: LtpUpdateMightCauseOperationClientBeingRemovedFromLink
    uuid: alt-2-0-1-op-fc-is-003
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - service-name: /v1/update-ltp
        uuid: alt-2-0-1-op-s-is-005
    consequent-requests:
      - service-name: ApplicationLayerTopology://v1/remove-operation-client-from-link
        uuid: alt-2-0-1-op-c-is-alt-2-0-1-001
```
