### ISSUE TITLE
typo: release number mismatch in operation-uuid and release-number of example

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#509]
In line 3911, /v1/list-end-points-of-link :: response :: example, the release-number attribute has value as 2.0.1 but the operation-uuid has release-number as 2-1-0. This release-number could be updated as 2.1.0, so the release-number and operation-uuid match.

```
               link-end-point-list:
                    - application-name: 'RegistryOffice'
                      release-number: '2.1.0'
                      operation-uuid: 'ro-2-1-0-op-c-im-alt-2-1-0-000'
                      ltp-direction: 'core-model-1-4:TERMINATION_DIRECTION_SINK'
                    - application-name: 'ApplicationLayerTopology'
                      release-number: '2.1.0'
                      operation-uuid: 'alt-2-1-0-op-s-bm-001'
                      ltp-direction: 'core-model-1-4:TERMINATION_DIRECTION_SOURCE'
```
