### ISSUE TITLE
domain name to be added

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationLayerTopology#54]
Data structure of the TcpClient and TcpServer shall be complemented by a domainName attribute for preparing potential future appliance of a DNS function.

Modelling has to assure that there is either IP address or domain name communicated and stored.

The following elements of the OAS have to be changed:
  - [ ] all service bodies containing *address and *port
  - [ ] all service body examples containing *address and *port
  - [ ] all service response bodies containing *address and *port
  - [ ] all service response body examples containing *address and *port
  - [ ] all callbacks bodies containing *address and *port
  - [ ] all callbacks body examples containing *address and *port
  - [ ] all callbacks response bodies containing *address and *port
  - [ ] all callbacks response body examples containing *address and *port
  - [ ] control-construct :: tcp-server
  - [ ] control-construct :: tcp-client

Coding examples:
```
ip-address:
  type: object
  minProperties: 1
  additionalProperties: false
  properties:
    ipv-4-address:
      type: string
      pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      description: >
        '..'
domain-name:
  type: string
  pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$'
  description: >
    '..'
```

```
example:
  new-application-name: 'NewApplicationName'
  new-application-release: '0.0.2'
  new-application-address:
    ip-address:
      ipv-4-address: '10.118.125.157'
  new-application-port: 7000
```

Further details can be found in the callbacks inside the ApplicationPattern OAS.
